## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
notifications:
  email: false
matrix:
  include:
    - os: linux
      julia: 0.6
    - os: linux
      julia: nightly
  allow_failures:
    - julia: nightly

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("Knockout")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("Knockout")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
